# This is the start of the budget platform.
# You should be able to manage your budget
# and analyze where your money is going.
# This progran should also help with planning expesnses as well
# Good Luck!
# Please do not edit this file

##########  Python IMPORTs  ############################################################
import sys
########################################################################################

##########  Created files IMPORTS  #####################################################
import logger
from main_handler import Start
########################################################################################
# Set up logger
log = logger.main()

if __name__ == "__main__": 

    start = Start(log)
