# This is the start of the budget platform.
# You should be able to manage your budget
# and analyze where your money is going.
# This progran should also help with planning expesnses as well
# Good Luck!
# Please do not edit this file

##########  Python IMPORTs  ############################################################
from PyQt6.QtWidgets import QApplication
import sys
########################################################################################

##########  Created files IMPORTS  #####################################################
from main_handler import Start
########################################################################################

if __name__ == "__main__":

    app = QApplication(sys.argv)
    start = Start()
    sys.exit(app.exec())