# Form implementation generated from reading ui file 'side_menu.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtWidgets import (QWidget, 
                             QLabel,
                             QApplication, 
                             QPushButton)
from PyQt6.QtCore import (QRect,
                          Qt, 
                          QMetaObject, 
                          QCoreApplication)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 1030)
        Form.setStyleSheet("\n"
"QWidget {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #3a3a3a;\n"
"    width: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.menu_label = QLabel(parent=Form)
        self.menu_label.setGeometry(QRect(110, 20, 111, 51))
        self.menu_label.setStyleSheet("font: 26pt \"Nirmala UI\";")
        self.menu_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.menu_label.setObjectName("menu_label")
        self.dashboard_pushButton = QPushButton(parent=Form)
        self.dashboard_pushButton.setGeometry(QRect(70, 120, 200, 50))
        self.dashboard_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.dashboard_pushButton.setObjectName("dashboard_pushButton")
        self.calendar_pushButton = QPushButton(parent=Form)
        self.calendar_pushButton.setGeometry(QRect(70, 200, 200, 50))
        self.calendar_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.calendar_pushButton.setObjectName("calendar_pushButton")
        self.transaction_pushButton = QPushButton(parent=Form)
        self.transaction_pushButton.setGeometry(QRect(70, 280, 200, 50))
        self.transaction_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.transaction_pushButton.setObjectName("transaction_pushButton")
        self.monthly_budget_pushButton = QPushButton(parent=Form)
        self.monthly_budget_pushButton.setGeometry(QRect(70, 360, 200, 50))
        self.monthly_budget_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.monthly_budget_pushButton.setObjectName("monthly_budget_pushButton")
        self.portfolio_pushButton = QPushButton(parent=Form)
        self.portfolio_pushButton.setGeometry(QRect(70, 440, 200, 50))
        self.portfolio_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.portfolio_pushButton.setObjectName("portfolio_pushButton")
        self.budget_planning_pushButton = QPushButton(parent=Form)
        self.budget_planning_pushButton.setGeometry(QRect(70, 520, 200, 50))
        self.budget_planning_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.budget_planning_pushButton.setObjectName("budget_planning_pushButton")
        self.spending_planning_pushButton = QPushButton(parent=Form)
        self.spending_planning_pushButton.setGeometry(QRect(70, 600, 200, 50))
        self.spending_planning_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.spending_planning_pushButton.setObjectName("spending_planning_pushButton")

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.menu_label.setText(_translate("Form", "Menu"))
        self.dashboard_pushButton.setText(_translate("Form", "Dashboard"))
        self.calendar_pushButton.setText(_translate("Form", "Calendar"))
        self.transaction_pushButton.setText(_translate("Form", "Transactions"))
        self.monthly_budget_pushButton.setText(_translate("Form", "Monthly Budget"))
        self.portfolio_pushButton.setText(_translate("Form", "Portfolio"))
        self.budget_planning_pushButton.setText(_translate("Form", "Budget Planning"))
        self.spending_planning_pushButton.setText(_translate("Form", "Spending Planning"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Form = QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
