# Form implementation generated from reading ui file 'add_transaction_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1491, 401)
        Form.setStyleSheet("QWidget {\n"
"        background-color: #2c2c2c;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font: 14pt \"Nirmala UI\";\n"
"}\n"
"QWidget#side_menu {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Dashboard_Title {\n"
"    background-color: none;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    font: 20pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Eat_Out_Image {\n"
"    background-image: url(:/images/pngaaa.com-2384833.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Grocery_Image {\n"
"    background-image: url(:/images/pngaaa.com-2138453.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Transportation_Image {\n"
"    background-image: url(:/images/pngaaa.com-2182093.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Free_Expense_Image {\n"
"    background-image: url(:/images/pngaaa.com-1261106.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Bills_Image {\n"
"    background-image: url(:/images/pngaaa.com-1433501.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Investment_Image {\n"
"    background-image: url(:/images/pngaaa.com-3584133.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Support_Image {\n"
"    background-image: url(:/images/pngaaa.com-2914571.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Goal_Image {\n"
"    background-image: url(:/images/pngaaa.com-848656.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:hover {\n"
"    background-image: url(:/button_image/Burger_button_hover.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:pressed {\n"
"    background-image: url(:/button_image/Burger_button_click.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#remove_button_watchlist {\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#remove_button_watchlist:hover {\n"
"    background-color: #ff6c6c;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#remove_button_watchlist:pressed {\n"
"    background-color: #aa0000;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Add_strategy:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Activation {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Activation:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Activation:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Blue_button {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Blue_button:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Blue_button:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Yellow_button {\n"
"    background-color: #a5bd1e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Yellow_button:hover {\n"
"    background-color: #e5ff54;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Yellow_button:pressed {\n"
"    background-color: #81960f;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #3a3a3a;\n"
"    width: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.account_label = QtWidgets.QLabel(parent=Form)
        self.account_label.setGeometry(QtCore.QRect(20, 80, 91, 31))
        self.account_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.account_label.setObjectName("account_label")
        self.transfer_To_comboBox = QtWidgets.QComboBox(parent=Form)
        self.transfer_To_comboBox.setGeometry(QtCore.QRect(630, 230, 411, 31))
        self.transfer_To_comboBox.setObjectName("transfer_To_comboBox")
        self.transfer_To_comboBox.addItem("")
        self.description_label = QtWidgets.QLabel(parent=Form)
        self.description_label.setGeometry(QtCore.QRect(630, 80, 121, 31))
        self.description_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.description_label.setObjectName("description_label")
        self.amount_label = QtWidgets.QLabel(parent=Form)
        self.amount_label.setGeometry(QtCore.QRect(20, 190, 121, 31))
        self.amount_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.amount_label.setObjectName("amount_label")
        self.category_label = QtWidgets.QLabel(parent=Form)
        self.category_label.setGeometry(QtCore.QRect(340, 300, 141, 31))
        self.category_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.category_label.setObjectName("category_label")
        self.amount_doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=Form)
        self.amount_doubleSpinBox.setGeometry(QtCore.QRect(20, 230, 301, 41))
        self.amount_doubleSpinBox.setMaximum(1000000000.99)
        self.amount_doubleSpinBox.setSingleStep(0.01)
        self.amount_doubleSpinBox.setProperty("value", 0.00)
        self.amount_doubleSpinBox.setObjectName("amount_doubleSpinBox")
        self.date_label = QtWidgets.QLabel(parent=Form)
        self.date_label.setGeometry(QtCore.QRect(340, 80, 91, 31))
        self.date_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.date_label.setObjectName("date_label")
        self.horizontal_line_2 = QtWidgets.QFrame(parent=Form)
        self.horizontal_line_2.setGeometry(QtCore.QRect(10, 280, 1481, 3))
        self.horizontal_line_2.setStyleSheet("background-color: rgb(85, 222, 0);")
        self.horizontal_line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.horizontal_line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.horizontal_line_2.setObjectName("horizontal_line_2")
        self.category_Type_comboBox = QtWidgets.QComboBox(parent=Form)
        self.category_Type_comboBox.setGeometry(QtCore.QRect(630, 340, 411, 41))
        self.category_Type_comboBox.setObjectName("category_Type_comboBox")
        self.category_Type_label = QtWidgets.QLabel(parent=Form)
        self.category_Type_label.setGeometry(QtCore.QRect(630, 300, 141, 31))
        self.category_Type_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.category_Type_label.setObjectName("category_Type_label")
        self.discard_pushButton = QtWidgets.QPushButton(parent=Form)
        self.discard_pushButton.setGeometry(QtCore.QRect(1290, 340, 161, 41))
        self.discard_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #c30000;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ff5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8c0000;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.discard_pushButton.setObjectName("discard_pushButton")
        self.description_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.description_lineEdit.setGeometry(QtCore.QRect(630, 120, 621, 41))
        self.description_lineEdit.setObjectName("description_lineEdit")
        self.horizontal_line_1 = QtWidgets.QFrame(parent=Form)
        self.horizontal_line_1.setGeometry(QtCore.QRect(10, 175, 1481, 3))
        self.horizontal_line_1.setStyleSheet("background-color: rgb(85, 222, 0);")
        self.horizontal_line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.horizontal_line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.horizontal_line_1.setObjectName("horizontal_line_1")
        self.sub_Category_label = QtWidgets.QLabel(parent=Form)
        self.sub_Category_label.setGeometry(QtCore.QRect(20, 300, 141, 31))
        self.sub_Category_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.sub_Category_label.setObjectName("sub_Category_label")
        self.add_pushButton = QtWidgets.QPushButton(parent=Form)
        self.add_pushButton.setGeometry(QtCore.QRect(1110, 340, 161, 41))
        self.add_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.add_pushButton.setObjectName("add_pushButton")
        self.add_sub_pushButton = QtWidgets.QPushButton(parent=Form)
        self.add_sub_pushButton.setGeometry(QtCore.QRect(180, 305, 30, 30))
        self.add_sub_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.add_sub_pushButton.setObjectName("add_sub_pushButton")
        self.payback_pushButton = QtWidgets.QPushButton(parent=Form)
        self.payback_pushButton.setGeometry(QtCore.QRect(1110, 290, 161, 41))
        self.payback_pushButton.setStyleSheet("""QPushButton {
                                    background-color: #000277;
                                    border: 1px solid #a3a3a3;
                                    border-radius: 4px;
                                    color: #ffffff;
                                    padding: 5px;
                                    }""" )
        self.payback_pushButton.setObjectName("payback_pushButton")
        self.payback_pushButton.setEnabled(False)
        self.remove_pushButton = QtWidgets.QPushButton(parent=Form)
        self.remove_pushButton.setGeometry(QtCore.QRect(1290, 290, 161, 41))
        self.remove_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #c30000;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    font: 200 12pt\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ff5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8c0000;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.add_Transaction_label = QtWidgets.QLabel(parent=Form)
        self.add_Transaction_label.setGeometry(QtCore.QRect(20, 10, 241, 51))
        self.add_Transaction_label.setStyleSheet("font: 700 22pt \"Nirmala UI\";\n"
"")
        self.add_Transaction_label.setObjectName("add_Transaction_label")
        self.transfer_To_label = QtWidgets.QLabel(parent=Form)
        self.transfer_To_label.setGeometry(QtCore.QRect(630, 190, 121, 31))
        self.transfer_To_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.transfer_To_label.setObjectName("transfer_To_label")
        self.transfer_to_pushButton = QtWidgets.QPushButton(parent=Form)
        self.transfer_to_pushButton.setGeometry(QtCore.QRect(762, 190, 30, 30))
        self.transfer_to_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.transfer_to_pushButton.setObjectName("transfer_to_pushButton")
        self.sub_Category_comboBox = QtWidgets.QComboBox(parent=Form)
        self.sub_Category_comboBox.setGeometry(QtCore.QRect(20, 340, 301, 41))
        self.sub_Category_comboBox.setObjectName("sub_Category_comboBox")
        self.credit_Debit_label = QtWidgets.QLabel(parent=Form)
        self.credit_Debit_label.setGeometry(QtCore.QRect(340, 190, 121, 31))
        self.credit_Debit_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.credit_Debit_label.setObjectName("credit_Debit_label")
        self.account_comboBox = QtWidgets.QComboBox(parent=Form)
        self.account_comboBox.setGeometry(QtCore.QRect(20, 120, 301, 31))
        self.account_comboBox.setObjectName("account_comboBox")
        self.category_comboBox = QtWidgets.QComboBox(parent=Form)
        self.category_comboBox.setGeometry(QtCore.QRect(340, 340, 271, 41))
        self.category_comboBox.setObjectName("category_comboBox")
        self.date_dateEdit = QtWidgets.QDateEdit(parent=Form)
        self.date_dateEdit.setGeometry(QtCore.QRect(340, 120, 271, 31))
        self.date_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_dateEdit.setMaximumDate(QtCore.QDate(2024, 12, 31))
        self.date_dateEdit.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.date_dateEdit.setObjectName("date_dateEdit")
        self.credit_Debit_comboBox = QtWidgets.QComboBox(parent=Form)
        self.credit_Debit_comboBox.setGeometry(QtCore.QRect(340, 230, 271, 41))
        self.credit_Debit_comboBox.setObjectName("credit_Debit_comboBox")
        self.frequency_label = QtWidgets.QLabel(parent=Form)
        self.frequency_label.setGeometry(QtCore.QRect(1070, 190, 121, 31))
        self.frequency_label.setStyleSheet("font: 700 14pt \"Nirmala UI\";")
        self.frequency_label.setObjectName("frequency_label")
        self.frequency_comboBox = QtWidgets.QComboBox(parent=Form)
        self.frequency_comboBox.setGeometry(QtCore.QRect(1070, 230, 400, 31))
        self.frequency_comboBox.setObjectName("transfer_To_comboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.account_label.setText(_translate("Form", "Account"))
        self.transfer_To_comboBox.setItemText(0, _translate("Form", "None"))
        self.description_label.setText(_translate("Form", "Description"))
        self.amount_label.setText(_translate("Form", "Amount"))
        self.category_label.setText(_translate("Form", "Category"))
        self.date_label.setText(_translate("Form", "Date"))
        self.category_Type_label.setText(_translate("Form", "Category Type"))
        self.discard_pushButton.setText(_translate("Form", "Discard"))
        self.sub_Category_label.setText(_translate("Form", "Sub-Category"))
        self.add_pushButton.setText(_translate("Form", "Add"))
        self.payback_pushButton.setText(_translate("Form", "Payback"))
        self.remove_pushButton.setText(_translate("Form", "Remove Transaction"))
        self.add_Transaction_label.setText(_translate("Form", "Add Transaction"))
        self.transfer_To_label.setText(_translate("Form", "Transfer To"))
        self.credit_Debit_label.setText(_translate("Form", "Credit/Debit"))
        self.frequency_label.setText(_translate("Form", "Frequency"))
        self.add_sub_pushButton.setText(_translate("Form", "+"))
        self.transfer_to_pushButton.setText(_translate("Form", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
