# Form implementation generated from reading ui file 'budget_planning_plan.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(970, 835)
        Form.setStyleSheet("QWidget {\n"
"        background-color: #2c2c2c;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font: 14pt \"Nirmala UI\";\n"
"}\n"
"QWidget#side_menu {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Dashboard_Title {\n"
"    background-color: none;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    font: 20pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Eat_Out_Image {\n"
"    background-image: url(:/images/pngaaa.com-2384833.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Grocery_Image {\n"
"    background-image: url(:/images/pngaaa.com-2138453.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Transportation_Image {\n"
"    background-image: url(:/images/pngaaa.com-2182093.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Free_Expense_Image {\n"
"    background-image: url(:/images/pngaaa.com-1261106.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Bills_Image {\n"
"    background-image: url(:/images/pngaaa.com-1433501.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Investment_Image {\n"
"    background-image: url(:/images/pngaaa.com-3584133.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Support_Image {\n"
"    background-image: url(:/images/pngaaa.com-2914571.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Goal_Image {\n"
"    background-image: url(:/images/pngaaa.com-848656.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:hover {\n"
"    background-image: url(:/button_image/Burger_button_hover.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:pressed {\n"
"    background-image: url(:/button_image/Burger_button_click.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#remove_button_watchlist {\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#remove_button_watchlist:hover {\n"
"    background-color: #ff6c6c;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#remove_button_watchlist:pressed {\n"
"    background-color: #aa0000;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Add_strategy:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Activation {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Activation:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Activation:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Blue_button {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Blue_button:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Blue_button:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Yellow_button {\n"
"    background-color: #a5bd1e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Yellow_button:hover {\n"
"    background-color: #e5ff54;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Yellow_button:pressed {\n"
"    background-color: #81960f;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #3a3a3a;\n"
"    width: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.monthly_label = QtWidgets.QLabel(parent=Form)
        self.monthly_label.setGeometry(QtCore.QRect(10, 0, 950, 50))
        self.monthly_label.setMaximumSize(QtCore.QSize(950, 16777215))
        self.monthly_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 4px solid #000000;")
        self.monthly_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.monthly_label.setObjectName("monthly_label")
        self.add_frame = QtWidgets.QFrame(parent=Form)
        self.add_frame.setGeometry(QtCore.QRect(8, 500, 235, 49))
        self.add_frame.setStyleSheet("border: 1px solid #000000;\n"
"background-color: #000000;")
        self.add_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.add_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.add_frame.setObjectName("add_frame")
        self.add_pushButton = QtWidgets.QPushButton(parent=self.add_frame)
        self.add_pushButton.setGeometry(QtCore.QRect(65, 6, 100, 35))
        self.add_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.add_pushButton.setObjectName("add_pushButton")
        self.save_frame = QtWidgets.QFrame(parent=Form)
        self.save_frame.setGeometry(QtCore.QRect(489, 500, 235, 49))
        self.save_frame.setStyleSheet("border: 1px solid #000000;\n"
"background-color: #000000;")
        self.save_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.save_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.save_frame.setObjectName("save_frame")
        self.Save_pushButton = QtWidgets.QPushButton(parent=self.save_frame)
        self.Save_pushButton.setGeometry(QtCore.QRect(65, 6, 100, 35))
        self.Save_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.Save_pushButton.setObjectName("Save_pushButton")
        self.minus_frame = QtWidgets.QFrame(parent=Form)
        self.minus_frame.setGeometry(QtCore.QRect(249, 500, 234, 49))
        self.minus_frame.setStyleSheet("border: 1px solid #000000;\n"
"background-color: #000000;")
        self.minus_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.minus_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.minus_frame.setObjectName("minus_frame")
        self.minus_pushButton = QtWidgets.QPushButton(parent=self.minus_frame)
        self.minus_pushButton.setGeometry(QtCore.QRect(65, 6, 100, 35))
        self.minus_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #c30000;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ff5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8c0000;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.minus_pushButton.setObjectName("minus_pushButton")
        self.load_frame = QtWidgets.QFrame(parent=Form)
        self.load_frame.setGeometry(QtCore.QRect(730, 500, 233, 49))
        self.load_frame.setMaximumSize(QtCore.QSize(233, 16777215))
        self.load_frame.setStyleSheet("border: 1px solid #000000;\n"
"background-color: #000000;")
        self.load_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.load_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.load_frame.setObjectName("load_frame")
        self.load_pushButton = QtWidgets.QPushButton(parent=self.load_frame)
        self.load_pushButton.setGeometry(QtCore.QRect(65, 6, 100, 35))
        self.load_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.load_pushButton.setObjectName("load_pushButton")
        self.total_cost_label = QtWidgets.QLabel(parent=Form)
        self.total_cost_label.setGeometry(QtCore.QRect(489, 550, 474, 50))
        self.total_cost_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 1px solid #000000;")
        self.total_cost_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_cost_label.setObjectName("total_cost_label")
        self.total_label = QtWidgets.QLabel(parent=Form)
        self.total_label.setGeometry(QtCore.QRect(8, 550, 475, 50))
        self.total_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 1px solid #000000;")
        self.total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_label.setObjectName("total_label")
        self.lifstyle_need_label = QtWidgets.QLabel(parent=Form)
        self.lifstyle_need_label.setGeometry(QtCore.QRect(10, 610, 955, 49))
        self.lifstyle_need_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 4px solid #000000;")
        self.lifstyle_need_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lifstyle_need_label.setObjectName("lifstyle_need_label")
        self.hourly_wage_label = QtWidgets.QLabel(parent=Form)
        self.hourly_wage_label.setGeometry(QtCore.QRect(10, 775, 475, 50))
        self.hourly_wage_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 1px solid #000000;")
        self.hourly_wage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hourly_wage_label.setObjectName("hourly_wage_label")
        self.monthly_wage_label = QtWidgets.QLabel(parent=Form)
        self.monthly_wage_label.setGeometry(QtCore.QRect(10, 664, 475, 50))
        self.monthly_wage_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 1px solid #000000;")
        self.monthly_wage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.monthly_wage_label.setObjectName("monthly_wage_label")
        self.bi_weekly_wage_cost_label = QtWidgets.QLabel(parent=Form)
        self.bi_weekly_wage_cost_label.setGeometry(QtCore.QRect(491, 720, 474, 49))
        self.bi_weekly_wage_cost_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 1px solid #000000;")
        self.bi_weekly_wage_cost_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bi_weekly_wage_cost_label.setObjectName("bi_weekly_wage_cost_label")
        self.hourly_wage_cost_label = QtWidgets.QLabel(parent=Form)
        self.hourly_wage_cost_label.setGeometry(QtCore.QRect(491, 775, 474, 50))
        self.hourly_wage_cost_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 1px solid #000000;")
        self.hourly_wage_cost_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hourly_wage_cost_label.setObjectName("hourly_wage_cost_label")
        self.monthly_wage_cost_label = QtWidgets.QLabel(parent=Form)
        self.monthly_wage_cost_label.setGeometry(QtCore.QRect(491, 664, 474, 50))
        self.monthly_wage_cost_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 1px solid #000000;")
        self.monthly_wage_cost_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.monthly_wage_cost_label.setObjectName("monthly_wage_cost_label")
        self.bi_weekly_wage_label = QtWidgets.QLabel(parent=Form)
        self.bi_weekly_wage_label.setGeometry(QtCore.QRect(10, 720, 475, 49))
        self.bi_weekly_wage_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 1px solid #000000;")
        self.bi_weekly_wage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bi_weekly_wage_label.setObjectName("bi_weekly_wage_label")
        self.expenses_label = QtWidgets.QLabel(parent=Form)
        self.expenses_label.setGeometry(QtCore.QRect(10, 60, 230, 48))
        self.expenses_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 2.5px solid #000000;")
        self.expenses_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.expenses_label.setObjectName("expenses_label")
        self.input_label = QtWidgets.QLabel(parent=Form)
        self.input_label.setGeometry(QtCore.QRect(247, 60, 231, 48))
        self.input_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 2.5px solid #000000;")
        self.input_label.setText("")
        self.input_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_label.setObjectName("input_label")
        self.cost_label = QtWidgets.QLabel(parent=Form)
        self.cost_label.setGeometry(QtCore.QRect(484, 60, 230, 48))
        self.cost_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 2.5px solid #000000;")
        self.cost_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cost_label.setObjectName("cost_label")
        self.percentage_label = QtWidgets.QLabel(parent=Form)
        self.percentage_label.setGeometry(QtCore.QRect(720, 60, 230, 48))
        self.percentage_label.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: #7300ff;\n"
"border: 2.5px solid #000000;")
        self.percentage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.percentage_label.setObjectName("percentage_label")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 120, 955, 375))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 955, 400))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 400))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        # self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        # self.label.setGeometry(QtCore.QRect(90, 60, 101, 61))
        # self.label.setObjectName("label")
        # self.label.setText("JaJa")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.monthly_label.setText(_translate("Form", "Monthly"))
        self.add_pushButton.setText(_translate("Form", "+"))
        self.Save_pushButton.setText(_translate("Form", "Save"))
        self.minus_pushButton.setText(_translate("Form", "-"))
        self.load_pushButton.setText(_translate("Form", "Load"))
        self.total_cost_label.setText(_translate("Form", "$ - -"))
        self.total_label.setText(_translate("Form", "Total"))
        self.lifstyle_need_label.setText(_translate("Form", "Need for Lifestyle"))
        self.hourly_wage_label.setText(_translate("Form", "Average Hourly Wage (80 hrs)"))
        self.monthly_wage_label.setText(_translate("Form", "Monthly Wage (70% Take Home)"))
        self.bi_weekly_wage_cost_label.setText(_translate("Form", "$ - -"))
        self.hourly_wage_cost_label.setText(_translate("Form", "$ - -"))
        self.monthly_wage_cost_label.setText(_translate("Form", "$ - -"))
        self.bi_weekly_wage_label.setText(_translate("Form", "Average Bi-Weekly Wage (80 hrs)"))
        self.expenses_label.setText(_translate("Form", "Expenses"))
        self.cost_label.setText(_translate("Form", "Cost"))
        self.percentage_label.setText(_translate("Form", "Percentage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
