# Form implementation generated from reading ui file 'Dashboard_header_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtWidgets import (QWidget, QLabel, QFrame, QApplication)
from PyQt6.QtCore import (QRect, QMetaObject, QCoreApplication)
from PyQt6.QtGui import (QFont)

class Ui_Dashboard_header_widget(object):
    def setupUi(self, Dashboard_header_widget):
        Dashboard_header_widget.setObjectName("Dashboard_header_widget")
        Dashboard_header_widget.resize(1920, 130)
        Dashboard_header_widget.setStyleSheet("QWidget {\n"
"        background-color: #2c2c2c;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font: 14pt \"Nirmala UI\";\n"
"}\n"
"QWidget#side_menu {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Dashboard_Title {\n"
"    background-color: none;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    font: 20pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Eat_Out_Image {\n"
"    background-image: url(:/images/pngaaa.com-2384833.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Grocery_Image {\n"
"    background-image: url(:/images/pngaaa.com-2138453.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Transportation_Image {\n"
"    background-image: url(:/images/pngaaa.com-2182093.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Free_Expense_Image {\n"
"    background-image: url(:/images/pngaaa.com-1261106.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Bills_Image {\n"
"    background-image: url(:/images/pngaaa.com-1433501.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Investment_Image {\n"
"    background-image: url(:/images/pngaaa.com-3584133.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Support_Image {\n"
"    background-image: url(:/images/pngaaa.com-2914571.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Goal_Image {\n"
"    background-image: url(:/images/pngaaa.com-848656.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:hover {\n"
"    background-image: url(:/button_image/Burger_button_hover.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:pressed {\n"
"    background-image: url(:/button_image/Burger_button_click.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#remove_button_watchlist {\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#remove_button_watchlist:hover {\n"
"    background-color: #ff6c6c;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#remove_button_watchlist:pressed {\n"
"    background-color: #aa0000;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Add_strategy:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Activation {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Activation:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Activation:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Blue_button {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Blue_button:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Blue_button:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Yellow_button {\n"
"    background-color: #a5bd1e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Yellow_button:hover {\n"
"    background-color: #e5ff54;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Yellow_button:pressed {\n"
"    background-color: #81960f;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #3a3a3a;\n"
"    width: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.label = QLabel(parent=Dashboard_header_widget)
        self.label.setGeometry(QRect(10, 30, 341, 41))
        font = QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 700 26pt \"Arial\";")
        self.label.setObjectName("label")
        self.ytd_label = QLabel(parent=Dashboard_header_widget)
        self.ytd_label.setGeometry(QRect(370, 40, 101, 31))
        self.ytd_label.setObjectName("ytd_label")
        self.eating_out_Image_label = QLabel(parent=Dashboard_header_widget)
        self.eating_out_Image_label.setGeometry(QRect(490, 10, 61, 61))
        self.eating_out_Image_label.setObjectName("eating_out_Image_label")
        self.eating_out_Spent_label = QLabel(parent=Dashboard_header_widget)
        self.eating_out_Spent_label.setGeometry(QRect(560, 30, 91, 31))
        self.eating_out_Spent_label.setText("")
        self.eating_out_Spent_label.setObjectName("eating_out_Spent_label")
        self.eating_out_label = QLabel(parent=Dashboard_header_widget)
        self.eating_out_label.setGeometry(QRect(490, 80, 161, 31))
        self.eating_out_label.setObjectName("eating_out_label")
        self.grocery_Image_label = QLabel(parent=Dashboard_header_widget)
        self.grocery_Image_label.setGeometry(QRect(670, 10, 61, 61))
        self.grocery_Image_label.setObjectName("grocery_Image_label")
        self.grocery_Spent_label = QLabel(parent=Dashboard_header_widget)
        self.grocery_Spent_label.setGeometry(QRect(740, 30, 91, 31))
        self.grocery_Spent_label.setText("")
        self.grocery_Spent_label.setObjectName("grocery_Spent_label")
        self.grocery_label = QLabel(parent=Dashboard_header_widget)
        self.grocery_label.setGeometry(QRect(670, 80, 161, 31))
        self.grocery_label.setObjectName("grocery_label")
        self.transportation_Image_label = QLabel(parent=Dashboard_header_widget)
        self.transportation_Image_label.setGeometry(QRect(850, 10, 61, 61))
        self.transportation_Image_label.setObjectName("transportation_Image_label")
        self.transportation_Spent_label = QLabel(parent=Dashboard_header_widget)
        self.transportation_Spent_label.setGeometry(QRect(920, 30, 91, 31))
        self.transportation_Spent_label.setText("")
        self.transportation_Spent_label.setObjectName("transportation_Spent_label")
        self.transportation_label = QLabel(parent=Dashboard_header_widget)
        self.transportation_label.setGeometry(QRect(850, 80, 161, 31))
        self.transportation_label.setObjectName("transportation_label")
        self.free_Expense_Image_label = QLabel(parent=Dashboard_header_widget)
        self.free_Expense_Image_label.setGeometry(QRect(1030, 10, 61, 61))
        self.free_Expense_Image_label.setObjectName("free_Expense_Image_label")
        self.free_expense_Spent_label = QLabel(parent=Dashboard_header_widget)
        self.free_expense_Spent_label.setGeometry(QRect(1100, 30, 91, 31))
        self.free_expense_Spent_label.setText("")
        self.free_expense_Spent_label.setObjectName("free_expense_Spent_label")
        self.free_Expense_label = QLabel(parent=Dashboard_header_widget)
        self.free_Expense_label.setGeometry(QRect(1030, 80, 161, 31))
        self.free_Expense_label.setObjectName("free_Expense_label")
        self.investment_label = QLabel(parent=Dashboard_header_widget)
        self.investment_label.setGeometry(QRect(1210, 80, 161, 31))
        self.investment_label.setObjectName("investment_label")
        self.investment_Image_label = QLabel(parent=Dashboard_header_widget)
        self.investment_Image_label.setGeometry(QRect(1210, 10, 61, 61))
        self.investment_Image_label.setObjectName("investment_Image_label")
        self.investment_Spent_label = QLabel(parent=Dashboard_header_widget)
        self.investment_Spent_label.setGeometry(QRect(1280, 30, 91, 31))
        self.investment_Spent_label.setText("")
        self.investment_Spent_label.setObjectName("investment_Spent_label")
        self.bills_Spent_label = QLabel(parent=Dashboard_header_widget)
        self.bills_Spent_label.setGeometry(QRect(1460, 30, 91, 31))
        self.bills_Spent_label.setText("")
        self.bills_Spent_label.setObjectName("bills_Spent_label")
        self.bills_label = QLabel(parent=Dashboard_header_widget)
        self.bills_label.setGeometry(QRect(1390, 80, 161, 31))
        self.bills_label.setObjectName("bills_label")
        self.bills_Image_label = QLabel(parent=Dashboard_header_widget)
        self.bills_Image_label.setGeometry(QRect(1390, 10, 61, 61))
        self.bills_Image_label.setObjectName("bills_Image_label")
        self.support_Spent_label = QLabel(parent=Dashboard_header_widget)
        self.support_Spent_label.setGeometry(QRect(1640, 30, 91, 31))
        self.support_Spent_label.setText("")
        self.support_Spent_label.setObjectName("support_Spent_label")
        self.support_label = QLabel(parent=Dashboard_header_widget)
        self.support_label.setGeometry(QRect(1570, 80, 161, 31))
        self.support_label.setObjectName("support_label")
        self.support_Image_label = QLabel(parent=Dashboard_header_widget)
        self.support_Image_label.setGeometry(QRect(1570, 10, 61, 61))
        self.support_Image_label.setObjectName("support_Image_label")
        self.bills_Spent_label_2 = QLabel(parent=Dashboard_header_widget)
        self.bills_Spent_label_2.setGeometry(QRect(1820, 30, 91, 31))
        self.bills_Spent_label_2.setText("")
        self.bills_Spent_label_2.setObjectName("bills_Spent_label_2")
        self.goal_label = QLabel(parent=Dashboard_header_widget)
        self.goal_label.setGeometry(QRect(1750, 80, 161, 31))
        self.goal_label.setObjectName("goal_label")
        self.goal_Image_label = QLabel(parent=Dashboard_header_widget)
        self.goal_Image_label.setGeometry(QRect(1750, 10, 61, 61))
        self.goal_Image_label.setObjectName("goal_Image_label")
        self.line = QFrame(parent=Dashboard_header_widget)
        self.line.setGeometry(QRect(0, 125, 1920, 10))
        self.line.setStyleSheet("background-color: #181818;")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dashboard_header_widget)
        QMetaObject.connectSlotsByName(Dashboard_header_widget)

    def retranslateUi(self, Dashboard_header_widget):
        _translate = QCoreApplication.translate
        Dashboard_header_widget.setWindowTitle(_translate("Dashboard_header_widget", "Form"))
        self.label.setText(_translate("Dashboard_header_widget", "Financial Dashboard"))
        self.ytd_label.setText(_translate("Dashboard_header_widget", "Spend YTD:"))
        self.eating_out_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/eating_out_label_61x61.png\"/></p></body></html>"))
        self.eating_out_label.setText(_translate("Dashboard_header_widget", "Eating-Out"))
        self.grocery_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/grocery_label_61x61.png\"/></p></body></html>"))
        self.grocery_label.setText(_translate("Dashboard_header_widget", "Grocery"))
        self.transportation_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/transportation_label_61x61.png\"/></p></body></html>"))
        self.transportation_label.setText(_translate("Dashboard_header_widget", "Transportation"))
        self.free_Expense_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/Free_expense_label_61x61.png\"/></p></body></html>"))
        self.free_Expense_label.setText(_translate("Dashboard_header_widget", "Free Expense"))
        self.investment_label.setText(_translate("Dashboard_header_widget", "Investment"))
        self.investment_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/investments_label_61x61.png\"/></p></body></html>"))
        self.bills_label.setText(_translate("Dashboard_header_widget", "Bills"))
        self.bills_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/bills_label_61x61.png\"/></p></body></html>"))
        self.support_label.setText(_translate("Dashboard_header_widget", "Support"))
        self.support_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/support_label_61x61.png\"/></p></body></html>"))
        self.goal_label.setText(_translate("Dashboard_header_widget", "Goal"))
        self.goal_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/goal_label_61x61.png\"/></p></body></html>"))
