# Form implementation generated from reading ui file 'month_progress_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1910, 251)
        Form.setStyleSheet("QWidget {\n"
"        background-color: #2c2c2c;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font: 14pt \"Nirmala UI\";\n"
"}\n"
"QWidget#side_menu {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Dashboard_Title {\n"
"    background-color: none;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    font: 20pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Eat_Out_Image {\n"
"    background-image: url(:/images/pngaaa.com-2384833.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Grocery_Image {\n"
"    background-image: url(:/images/pngaaa.com-2138453.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Transportation_Image {\n"
"    background-image: url(:/images/pngaaa.com-2182093.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Free_Expense_Image {\n"
"    background-image: url(:/images/pngaaa.com-1261106.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Bills_Image {\n"
"    background-image: url(:/images/pngaaa.com-1433501.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Investment_Image {\n"
"    background-image: url(:/images/pngaaa.com-3584133.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Support_Image {\n"
"    background-image: url(:/images/pngaaa.com-2914571.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Goal_Image {\n"
"    background-image: url(:/images/pngaaa.com-848656.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:hover {\n"
"    background-image: url(:/button_image/Burger_button_hover.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:pressed {\n"
"    background-image: url(:/button_image/Burger_button_click.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#remove_button_watchlist {\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#remove_button_watchlist:hover {\n"
"    background-color: #ff6c6c;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#remove_button_watchlist:pressed {\n"
"    background-color: #aa0000;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Add_strategy:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Activation {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Activation:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Activation:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Blue_button {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Blue_button:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Blue_button:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Yellow_button {\n"
"    background-color: #a5bd1e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Yellow_button:hover {\n"
"    background-color: #e5ff54;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Yellow_button:pressed {\n"
"    background-color: #81960f;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: QLinearGradient(" 
"        x1: 0, y1: 0,"
"        x2: 1, y2: 0,"
"        stop: 0.539773 rgba(5, 220, 48, 255),"
"        stop: 1 rgba(2, 138, 0, 255) );\n"
"        border-radius: 7px;\n"
"    "
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.month_col_Investment_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Investment_label.setGeometry(QtCore.QRect(950, 81, 161, 37))
        self.month_col_Investment_label.setObjectName("month_col_Investment_label")
        self.income_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.income_progressBar.setGeometry(QtCore.QRect(113, 210, 161, 27))
        self.income_progressBar.setProperty("value", 24)
        self.income_progressBar.setObjectName("income_progressBar")
        self.spent_col_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_label.setGeometry(QtCore.QRect(7, 124, 100, 37))
        self.spent_col_label.setObjectName("spent_col_label")
        self.left_col_Transportation_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Transportation_label.setGeometry(QtCore.QRect(615, 167, 162, 37))
        self.left_col_Transportation_label.setObjectName("left_col_Transportation_label")
        self.transportation_progress_label = QtWidgets.QLabel(parent=Form)
        self.transportation_progress_label.setGeometry(QtCore.QRect(615, 38, 162, 37))
        self.transportation_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.transportation_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.transportation_progress_label.setObjectName("transportation_progress_label")
        self.spent_col_Eating_Out_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Eating_Out_label.setGeometry(QtCore.QRect(280, 124, 162, 37))
        self.spent_col_Eating_Out_label.setObjectName("spent_col_Eating_Out_label")
        self.left_col_Free_Expense_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Free_Expense_label.setGeometry(QtCore.QRect(783, 167, 161, 37))
        self.left_col_Free_Expense_label.setObjectName("left_col_Free_Expense_label")
        self.bill_progress_label = QtWidgets.QLabel(parent=Form)
        self.bill_progress_label.setGeometry(QtCore.QRect(1117, 38, 162, 37))
        self.bill_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.bill_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bill_progress_label.setObjectName("bill_progress_label")
        self.left_col_Bills_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Bills_label.setGeometry(QtCore.QRect(1117, 167, 162, 37))
        self.left_col_Bills_label.setObjectName("left_col_Bills_label")
        self.spent_col_Investment_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Investment_label.setGeometry(QtCore.QRect(950, 124, 161, 37))
        self.spent_col_Investment_label.setObjectName("spent_col_Investment_label")
        self.spent_col_Transportation_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Transportation_label.setGeometry(QtCore.QRect(615, 124, 162, 37))
        self.spent_col_Transportation_label.setObjectName("spent_col_Transportation_label")
        self.month_col_Eating_Out_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Eating_Out_label.setGeometry(QtCore.QRect(280, 81, 162, 37))
        self.month_col_Eating_Out_label.setObjectName("month_col_Eating_Out_label")
        self.left_col_Sum_Total_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Sum_Total_label.setGeometry(QtCore.QRect(1620, 167, 161, 37))
        self.left_col_Sum_Total_label.setObjectName("left_col_Sum_Total_label")
        self.left_col_Goal_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Goal_label.setGeometry(QtCore.QRect(1452, 167, 162, 37))
        self.left_col_Goal_label.setObjectName("left_col_Goal_label")
        self.eating_out_progress_label = QtWidgets.QLabel(parent=Form)
        self.eating_out_progress_label.setGeometry(QtCore.QRect(280, 38, 162, 37))
        self.eating_out_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.eating_out_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.eating_out_progress_label.setObjectName("eating_out_progress_label")
        self.left_col_Groceries_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Groceries_label.setGeometry(QtCore.QRect(448, 167, 161, 37))
        self.left_col_Groceries_label.setObjectName("left_col_Groceries_label")
        self.spent_col_Sum_Total_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Sum_Total_label.setGeometry(QtCore.QRect(1620, 124, 161, 37))
        self.spent_col_Sum_Total_label.setObjectName("spent_col_Sum_Total_label")
        self.free_expense_progress_label = QtWidgets.QLabel(parent=Form)
        self.free_expense_progress_label.setGeometry(QtCore.QRect(783, 38, 161, 37))
        self.free_expense_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.free_expense_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.free_expense_progress_label.setObjectName("free_expense_progress_label")
        self.month_progress_comboBox = QtWidgets.QComboBox(parent=Form)
        self.month_progress_comboBox.setGeometry(QtCore.QRect(7, 4, 267, 28))
        self.month_progress_comboBox.setObjectName("month_progress_comboBox")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_progress_comboBox.addItem("")
        self.month_col_Goal_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Goal_label.setGeometry(QtCore.QRect(1452, 81, 162, 37))
        self.month_col_Goal_label.setObjectName("month_col_Goal_label")
        self.left_col_label = QtWidgets.QLabel(parent=Form)
        self.left_col_label.setGeometry(QtCore.QRect(7, 167, 100, 37))
        self.left_col_label.setObjectName("left_col_label")
        self.left_col_Eating_Out_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Eating_Out_label.setGeometry(QtCore.QRect(280, 167, 162, 37))
        self.left_col_Eating_Out_label.setObjectName("left_col_Eating_Out_label")
        self.left_col_Investment_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Investment_label.setGeometry(QtCore.QRect(950, 167, 161, 37))
        self.left_col_Investment_label.setObjectName("left_col_Investment_label")
        self.investment_progress_label = QtWidgets.QLabel(parent=Form)
        self.investment_progress_label.setGeometry(QtCore.QRect(950, 38, 161, 37))
        self.investment_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.investment_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.investment_progress_label.setObjectName("investment_progress_label")
        self.income_progress_label = QtWidgets.QLabel(parent=Form)
        self.income_progress_label.setGeometry(QtCore.QRect(113, 38, 161, 37))
        self.income_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.income_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.income_progress_label.setObjectName("income_progress_label")
        self.groceries_progress_label = QtWidgets.QLabel(parent=Form)
        self.groceries_progress_label.setGeometry(QtCore.QRect(448, 38, 161, 37))
        self.groceries_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.groceries_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groceries_progress_label.setObjectName("groceries_progress_label")
        self.month_col_Support_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Support_label.setGeometry(QtCore.QRect(1285, 81, 161, 37))
        self.month_col_Support_label.setObjectName("month_col_Support_label")
        self.investment_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.investment_progressBar.setGeometry(QtCore.QRect(950, 210, 161, 27))
        self.investment_progressBar.setProperty("value", 24)
        self.investment_progressBar.setObjectName("investment_progressBar")
        self.sum_Total_progress_label = QtWidgets.QLabel(parent=Form)
        self.sum_Total_progress_label.setGeometry(QtCore.QRect(1620, 38, 161, 37))
        self.sum_Total_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.sum_Total_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sum_Total_progress_label.setObjectName("sum_Total_progress_label")
        self.support_progress_label = QtWidgets.QLabel(parent=Form)
        self.support_progress_label.setGeometry(QtCore.QRect(1285, 38, 161, 37))
        self.support_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.support_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.support_progress_label.setObjectName("support_progress_label")
        self.spent_col_Profit_Loss_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Profit_Loss_label.setGeometry(QtCore.QRect(1787, 124, 112, 37))
        self.spent_col_Profit_Loss_label.setObjectName("spent_col_Profit_Loss_label")
        self.left_col_Support_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Support_label.setGeometry(QtCore.QRect(1285, 167, 161, 37))
        self.left_col_Support_label.setObjectName("left_col_Support_label")
        self.free_Expense_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.free_Expense_progressBar.setGeometry(QtCore.QRect(783, 210, 161, 27))
        self.free_Expense_progressBar.setProperty("value", 24)
        self.free_Expense_progressBar.setObjectName("free_Expense_progressBar")
        self.support_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.support_progressBar.setGeometry(QtCore.QRect(1285, 210, 161, 27))
        self.support_progressBar.setProperty("value", 24)
        self.support_progressBar.setObjectName("support_progressBar")
        self.month_col_label = QtWidgets.QLabel(parent=Form)
        self.month_col_label.setGeometry(QtCore.QRect(7, 81, 100, 37))
        self.month_col_label.setMinimumSize(QtCore.QSize(100, 0))
        self.month_col_label.setObjectName("month_col_label")
        self.eating_Out_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.eating_Out_progressBar.setGeometry(QtCore.QRect(280, 210, 162, 27))
        self.eating_Out_progressBar.setProperty("value", 24)
        self.eating_Out_progressBar.setObjectName("eating_Out_progressBar")
        self.month_col_Groceries_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Groceries_label.setGeometry(QtCore.QRect(448, 81, 161, 37))
        self.month_col_Groceries_label.setObjectName("month_col_Groceries_label")
        self.spent_col_Income_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Income_label.setGeometry(QtCore.QRect(113, 124, 161, 37))
        self.spent_col_Income_label.setObjectName("spent_col_Income_label")
        self.spent_col_Groceries_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Groceries_label.setGeometry(QtCore.QRect(448, 124, 161, 37))
        self.spent_col_Groceries_label.setObjectName("spent_col_Groceries_label")
        self.spent_col_Support_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Support_label.setGeometry(QtCore.QRect(1285, 124, 161, 37))
        self.spent_col_Support_label.setObjectName("spent_col_Support_label")
        self.month_col_Bills_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Bills_label.setGeometry(QtCore.QRect(1117, 81, 162, 37))
        self.month_col_Bills_label.setObjectName("month_col_Bills_label")
        self.month_progress_label = QtWidgets.QLabel(parent=Form)
        self.month_progress_label.setGeometry(QtCore.QRect(7, 38, 100, 37))
        self.month_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.month_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.month_progress_label.setObjectName("month_progress_label")
        self.month_col_Profit_Loss_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Profit_Loss_label.setGeometry(QtCore.QRect(1787, 81, 112, 37))
        self.month_col_Profit_Loss_label.setObjectName("month_col_Profit_Loss_label")
        self.goal_progress_label = QtWidgets.QLabel(parent=Form)
        self.goal_progress_label.setGeometry(QtCore.QRect(1452, 38, 162, 37))
        self.goal_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.goal_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.goal_progress_label.setObjectName("goal_progress_label")
        self.groceries_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.groceries_progressBar.setGeometry(QtCore.QRect(448, 210, 161, 27))
        self.groceries_progressBar.setProperty("value", 24)
        self.groceries_progressBar.setObjectName("groceries_progressBar")
        self.month_col_Transportation_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Transportation_label.setGeometry(QtCore.QRect(615, 81, 162, 37))
        self.month_col_Transportation_label.setObjectName("month_col_Transportation_label")
        self.month_col_Income_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Income_label.setGeometry(QtCore.QRect(113, 81, 161, 37))
        self.month_col_Income_label.setObjectName("month_col_Income_label")
        self.goal_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.goal_progressBar.setGeometry(QtCore.QRect(1452, 210, 162, 27))
        self.goal_progressBar.setProperty("value", 24)
        self.goal_progressBar.setObjectName("goal_progressBar")
        self.profit_Loss_progress_label = QtWidgets.QLabel(parent=Form)
        self.profit_Loss_progress_label.setGeometry(QtCore.QRect(1787, 38, 112, 37))
        self.profit_Loss_progress_label.setStyleSheet("background-color: rgb(85, 222, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt\n"
"")
        self.profit_Loss_progress_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.profit_Loss_progress_label.setObjectName("profit_Loss_progress_label")
        self.bills_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.bills_progressBar.setGeometry(QtCore.QRect(1117, 210, 162, 27))
        self.bills_progressBar.setProperty("value", 24)
        self.bills_progressBar.setObjectName("bills_progressBar")
        self.left_col_Income_label = QtWidgets.QLabel(parent=Form)
        self.left_col_Income_label.setGeometry(QtCore.QRect(113, 167, 161, 37))
        self.left_col_Income_label.setObjectName("left_col_Income_label")
        self.month_col_Free_Expense_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Free_Expense_label.setGeometry(QtCore.QRect(783, 81, 161, 37))
        self.month_col_Free_Expense_label.setObjectName("month_col_Free_Expense_label")
        self.sum_Total_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.sum_Total_progressBar.setGeometry(QtCore.QRect(1620, 210, 161, 27))
        self.sum_Total_progressBar.setProperty("value", 24)
        self.sum_Total_progressBar.setObjectName("sum_Total_progressBar")
        self.spent_col_Bills_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Bills_label.setGeometry(QtCore.QRect(1117, 124, 162, 37))
        self.spent_col_Bills_label.setObjectName("spent_col_Bills_label")
        self.spent_col_Goal_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Goal_label.setGeometry(QtCore.QRect(1452, 124, 162, 37))
        self.spent_col_Goal_label.setObjectName("spent_col_Goal_label")
        self.month_col_Sum_Total_label = QtWidgets.QLabel(parent=Form)
        self.month_col_Sum_Total_label.setGeometry(QtCore.QRect(1620, 81, 161, 37))
        self.month_col_Sum_Total_label.setObjectName("month_col_Sum_Total_label")
        self.spent_col_Free_Expense_label = QtWidgets.QLabel(parent=Form)
        self.spent_col_Free_Expense_label.setGeometry(QtCore.QRect(783, 124, 161, 37))
        self.spent_col_Free_Expense_label.setObjectName("spent_col_Free_Expense_label")
        self.transportation_progressBar = QtWidgets.QProgressBar(parent=Form)
        self.transportation_progressBar.setGeometry(QtCore.QRect(615, 210, 162, 27))
        self.transportation_progressBar.setProperty("value", 24)
        self.transportation_progressBar.setObjectName("transportation_progressBar")
        self.Stats_Year_comboBox = QtWidgets.QComboBox(parent=Form)
        self.Stats_Year_comboBox.setGeometry(QtCore.QRect(290, 4, 267, 28))
        self.Stats_Year_comboBox.setStyleSheet("font: 14pt \"Nirmala UI\";")
        self.Stats_Year_comboBox.setObjectName("Stats_Year_comboBox")
        self.Stats_Year_comboBox.addItem("")
        self.Stats_Year_comboBox.addItem("")
        self.Stats_Year_comboBox.addItem("")
        self.Stats_Year_comboBox.addItem("")
        self.Stats_Year_comboBox.addItem("")
        self.Stats_Year_comboBox.addItem("")
        self.Stats_Year_comboBox.addItem("")
        self.Stats_Year_comboBox.addItem("")
        self.Stats_Year_comboBox.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.month_col_Investment_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_label.setText(_translate("Form", "Spent"))
        self.left_col_Transportation_label.setText(_translate("Form", "$1,555,555.00"))
        self.transportation_progress_label.setText(_translate("Form", "Transportation"))
        self.spent_col_Eating_Out_label.setText(_translate("Form", "$1,555,555.00"))
        self.left_col_Free_Expense_label.setText(_translate("Form", "$1,555,555.00"))
        self.bill_progress_label.setText(_translate("Form", "Bills"))
        self.left_col_Bills_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Investment_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Transportation_label.setText(_translate("Form", "$1,555,555.00"))
        self.month_col_Eating_Out_label.setText(_translate("Form", "$1,555,555.00"))
        self.left_col_Sum_Total_label.setText(_translate("Form", "$1,555,555.00"))
        self.left_col_Goal_label.setText(_translate("Form", "$1,555,555.00"))
        self.eating_out_progress_label.setText(_translate("Form", "Eating Out"))
        self.left_col_Groceries_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Sum_Total_label.setText(_translate("Form", "$1,555,555.00"))
        self.free_expense_progress_label.setText(_translate("Form", "Free Expense"))
        self.month_progress_comboBox.setItemText(0, _translate("Form", "January"))
        self.month_progress_comboBox.setItemText(1, _translate("Form", "February"))
        self.month_progress_comboBox.setItemText(2, _translate("Form", "March"))
        self.month_progress_comboBox.setItemText(3, _translate("Form", "April"))
        self.month_progress_comboBox.setItemText(4, _translate("Form", "May"))
        self.month_progress_comboBox.setItemText(5, _translate("Form", "June"))
        self.month_progress_comboBox.setItemText(6, _translate("Form", "July"))
        self.month_progress_comboBox.setItemText(7, _translate("Form", "August"))
        self.month_progress_comboBox.setItemText(8, _translate("Form", "September"))
        self.month_progress_comboBox.setItemText(9, _translate("Form", "October"))
        self.month_progress_comboBox.setItemText(10, _translate("Form", "November"))
        self.month_progress_comboBox.setItemText(11, _translate("Form", "December"))
        self.month_col_Goal_label.setText(_translate("Form", "$1,555,555.00"))
        self.left_col_label.setText(_translate("Form", "Left"))
        self.left_col_Eating_Out_label.setText(_translate("Form", "$1,555,555.00"))
        self.left_col_Investment_label.setText(_translate("Form", "$1,555,555.00"))
        self.investment_progress_label.setText(_translate("Form", "Investment"))
        self.income_progress_label.setText(_translate("Form", "Income"))
        self.groceries_progress_label.setText(_translate("Form", "Groceries"))
        self.month_col_Support_label.setText(_translate("Form", "$1,555,555.00"))
        self.sum_Total_progress_label.setText(_translate("Form", "Sum Total"))
        self.support_progress_label.setText(_translate("Form", "Support"))
        self.spent_col_Profit_Loss_label.setText(_translate("Form", "$1,555,555.00"))
        self.left_col_Support_label.setText(_translate("Form", "$1,555,555.00"))
        self.month_col_label.setText(_translate("Form", "January"))
        self.month_col_Groceries_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Income_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Groceries_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Support_label.setText(_translate("Form", "$1,555,555.00"))
        self.month_col_Bills_label.setText(_translate("Form", "$1,555,555.00"))
        self.month_progress_label.setText(_translate("Form", "Month"))
        self.month_col_Profit_Loss_label.setText(_translate("Form", "$1,555,555.00"))
        self.goal_progress_label.setText(_translate("Form", "Goal"))
        self.month_col_Transportation_label.setText(_translate("Form", "$1,555,555.00"))
        self.month_col_Income_label.setText(_translate("Form", "$1,555,555.00"))
        self.profit_Loss_progress_label.setText(_translate("Form", "Profit/Loss"))
        self.left_col_Income_label.setText(_translate("Form", "$1,555,555.00"))
        self.month_col_Free_Expense_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Bills_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Goal_label.setText(_translate("Form", "$1,555,555.00"))
        self.month_col_Sum_Total_label.setText(_translate("Form", "$1,555,555.00"))
        self.spent_col_Free_Expense_label.setText(_translate("Form", "$1,555,555.00"))
        self.Stats_Year_comboBox.setItemText(0, _translate("Form", "2023"))
        self.Stats_Year_comboBox.setItemText(1, _translate("Form", "2022"))
        self.Stats_Year_comboBox.setItemText(2, _translate("Form", "2021"))
        self.Stats_Year_comboBox.setItemText(3, _translate("Form", "2020"))
        self.Stats_Year_comboBox.setItemText(4, _translate("Form", "2019"))
        self.Stats_Year_comboBox.setItemText(5, _translate("Form", "2018"))
        self.Stats_Year_comboBox.setItemText(6, _translate("Form", "2017"))
        self.Stats_Year_comboBox.setItemText(7, _translate("Form", "2016"))
        self.Stats_Year_comboBox.setItemText(8, _translate("Form", "2015"))