# Form implementation generated from reading ui file 'top_5_expense.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtWidgets import (QWidget, 
                             QLabel, 
                             QFrame, 
                             QVBoxLayout, 
                             QProgressBar, 
                             QHBoxLayout)
from PyQt6.QtCore import (QRect, 
                          QMetaObject, 
                          QCoreApplication, 
                          QSize)



class Ui_top_5_expense(object):
    def setupUi(self, top_5_expense):
        top_5_expense.setObjectName("top_5_expense")
        top_5_expense.resize(541, 281)
        top_5_expense.setStyleSheet("QWidget {\n"
"        background-color: #2c2c2c;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font: 14pt \"Nirmala UI\";\n"
"}\n"
"QWidget#side_menu {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Dashboard_Title {\n"
"    background-color: none;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    font: 20pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Eat_Out_Image {\n"
"    background-image: url(:/images/pngaaa.com-2384833.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Grocery_Image {\n"
"    background-image: url(:/images/pngaaa.com-2138453.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Transportation_Image {\n"
"    background-image: url(:/images/pngaaa.com-2182093.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Free_Expense_Image {\n"
"    background-image: url(:/images/pngaaa.com-1261106.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Bills_Image {\n"
"    background-image: url(:/images/pngaaa.com-1433501.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Investment_Image {\n"
"    background-image: url(:/images/pngaaa.com-3584133.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Support_Image {\n"
"    background-image: url(:/images/pngaaa.com-2914571.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Goal_Image {\n"
"    background-image: url(:/images/pngaaa.com-848656.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:hover {\n"
"    background-image: url(:/button_image/Burger_button_hover.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:pressed {\n"
"    background-image: url(:/button_image/Burger_button_click.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#remove_button_watchlist {\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#remove_button_watchlist:hover {\n"
"    background-color: #ff6c6c;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#remove_button_watchlist:pressed {\n"
"    background-color: #aa0000;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Add_strategy:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Activation {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Activation:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Activation:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Blue_button {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Blue_button:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Blue_button:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Yellow_button {\n"
"    background-color: #a5bd1e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Yellow_button:hover {\n"
"    background-color: #e5ff54;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Yellow_button:pressed {\n"
"    background-color: #81960f;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #3a3a3a;\n"
"    width: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.layoutWidget = QWidget(parent=top_5_expense)
        self.layoutWidget.setGeometry(QRect(350, 70, 181, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_Tops_Spent = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_Tops_Spent.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Tops_Spent.setObjectName("verticalLayout_Tops_Spent")
        self.top_1_progressBar = QProgressBar(parent=self.layoutWidget)
        self.top_1_progressBar.setMaximumSize(QSize(180, 16777215))
        self.top_1_progressBar.setProperty("value", 24)
        self.top_1_progressBar.setObjectName("top_1_progressBar")
        self.verticalLayout_Tops_Spent.addWidget(self.top_1_progressBar)
        self.top_2_progressBar = QProgressBar(parent=self.layoutWidget)
        self.top_2_progressBar.setMaximumSize(QSize(180, 16777215))
        self.top_2_progressBar.setProperty("value", 24)
        self.top_2_progressBar.setObjectName("top_2_progressBar")
        self.verticalLayout_Tops_Spent.addWidget(self.top_2_progressBar)
        self.top_3_progressBar = QProgressBar(parent=self.layoutWidget)
        self.top_3_progressBar.setMaximumSize(QSize(180, 16777215))
        self.top_3_progressBar.setProperty("value", 24)
        self.top_3_progressBar.setObjectName("top_3_progressBar")
        self.verticalLayout_Tops_Spent.addWidget(self.top_3_progressBar)
        self.top_4_progressBar = QProgressBar(parent=self.layoutWidget)
        self.top_4_progressBar.setMaximumSize(QSize(180, 16777215))
        self.top_4_progressBar.setProperty("value", 24)
        self.top_4_progressBar.setObjectName("top_4_progressBar")
        self.verticalLayout_Tops_Spent.addWidget(self.top_4_progressBar)
        self.top_5_progressBar = QProgressBar(parent=self.layoutWidget)
        self.top_5_progressBar.setMaximumSize(QSize(180, 16777215))
        self.top_5_progressBar.setProperty("value", 24)
        self.top_5_progressBar.setObjectName("top_5_progressBar")
        self.verticalLayout_Tops_Spent.addWidget(self.top_5_progressBar)
        self.layoutWidget_2 = QWidget(parent=top_5_expense)
        self.layoutWidget_2.setGeometry(QRect(0, 20, 541, 39))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_Titles = QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_Titles.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Titles.setObjectName("verticalLayout_Titles")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.top_5_label = QLabel(parent=self.layoutWidget_2)
        self.top_5_label.setObjectName("top_5_label")
        self.horizontalLayout.addWidget(self.top_5_label)
        self.top_5_Expense_label = QLabel(parent=self.layoutWidget_2)
        self.top_5_Expense_label.setObjectName("top_5_Expense_label")
        self.horizontalLayout.addWidget(self.top_5_Expense_label)
        self.empty_progress_bar_title_label = QLabel(parent=self.layoutWidget_2)
        self.empty_progress_bar_title_label.setText("")
        self.empty_progress_bar_title_label.setObjectName("empty_progress_bar_title_label")
        self.horizontalLayout.addWidget(self.empty_progress_bar_title_label)
        self.verticalLayout_Titles.addLayout(self.horizontalLayout)
        self.top_5_line = QFrame(parent=self.layoutWidget_2)
        self.top_5_line.setStyleSheet("background-color: rgb(85, 222, 0);")
        self.top_5_line.setFrameShape(QFrame.Shape.HLine)
        self.top_5_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.top_5_line.setObjectName("top_5_line")
        self.verticalLayout_Titles.addWidget(self.top_5_line)
        self.layoutWidget_3 = QWidget(parent=top_5_expense)
        self.layoutWidget_3.setGeometry(QRect(180, 70, 171, 161))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_Tops_spent = QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_Tops_spent.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Tops_spent.setObjectName("verticalLayout_Tops_spent")
        self.top_1_spent_label = QLabel(parent=self.layoutWidget_3)
        self.top_1_spent_label.setObjectName("top_1_spent_label")
        self.verticalLayout_Tops_spent.addWidget(self.top_1_spent_label)
        self.top_2_spent_label = QLabel(parent=self.layoutWidget_3)
        self.top_2_spent_label.setObjectName("top_2_spent_label")
        self.verticalLayout_Tops_spent.addWidget(self.top_2_spent_label)
        self.top_3_spent_label = QLabel(parent=self.layoutWidget_3)
        self.top_3_spent_label.setObjectName("top_3_spent_label")
        self.verticalLayout_Tops_spent.addWidget(self.top_3_spent_label)
        self.top_4_spent_label = QLabel(parent=self.layoutWidget_3)
        self.top_4_spent_label.setObjectName("top_4_spent_label")
        self.verticalLayout_Tops_spent.addWidget(self.top_4_spent_label)
        self.top_5_spent_label = QLabel(parent=self.layoutWidget_3)
        self.top_5_spent_label.setObjectName("top_5_spent_label")
        self.verticalLayout_Tops_spent.addWidget(self.top_5_spent_label)
        self.layoutWidget_4 = QWidget(parent=top_5_expense)
        self.layoutWidget_4.setGeometry(QRect(0, 70, 181, 161))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_Tops = QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_Tops.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Tops.setObjectName("verticalLayout_Tops")
        self.top_1_desc_label = QLabel(parent=self.layoutWidget_4)
        self.top_1_desc_label.setObjectName("top_1_desc_label")
        self.verticalLayout_Tops.addWidget(self.top_1_desc_label)
        self.top_2_desc_label = QLabel(parent=self.layoutWidget_4)
        self.top_2_desc_label.setObjectName("top_2_desc_label")
        self.verticalLayout_Tops.addWidget(self.top_2_desc_label)
        self.top_3_desc_label = QLabel(parent=self.layoutWidget_4)
        self.top_3_desc_label.setObjectName("top_3_desc_label")
        self.verticalLayout_Tops.addWidget(self.top_3_desc_label)
        self.top_4_desc_label = QLabel(parent=self.layoutWidget_4)
        self.top_4_desc_label.setObjectName("top_4_desc_label")
        self.verticalLayout_Tops.addWidget(self.top_4_desc_label)
        self.top_5_desc_label = QLabel(parent=self.layoutWidget_4)
        self.top_5_desc_label.setObjectName("top_5_desc_label")
        self.verticalLayout_Tops.addWidget(self.top_5_desc_label)

        self.retranslateUi(top_5_expense)
        QMetaObject.connectSlotsByName(top_5_expense)

    def retranslateUi(self, top_5_expense):
        _translate = QCoreApplication.translate
        top_5_expense.setWindowTitle(_translate("top_5_expense", "Form"))
        self.top_5_label.setText(_translate("top_5_expense", "Top 5"))
        self.top_5_Expense_label.setText(_translate("top_5_expense", "Expense"))
        self.top_1_spent_label.setText(_translate("top_5_expense", "$1,555,555.00"))
        self.top_2_spent_label.setText(_translate("top_5_expense", "$1,555,555.00"))
        self.top_3_spent_label.setText(_translate("top_5_expense", "$1,555,555.00"))
        self.top_4_spent_label.setText(_translate("top_5_expense", "$1,555,555.00"))
        self.top_5_spent_label.setText(_translate("top_5_expense", "$1,555,555.00"))
        self.top_1_desc_label.setText(_translate("top_5_expense", "Top 1"))
        self.top_2_desc_label.setText(_translate("top_5_expense", "Top 2"))
        self.top_3_desc_label.setText(_translate("top_5_expense", "Top 3"))
        self.top_4_desc_label.setText(_translate("top_5_expense", "Top 4"))
        self.top_5_desc_label.setText(_translate("top_5_expense", "Top 5"))