# Form implementation generated from reading ui file 'specifics_budget_planning_ex.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(910, 855)
        Form.setStyleSheet("QWidget {\n"
"        background-color: #2c2c2c;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font: 14pt \"Nirmala UI\";\n"
"}\n"
"QWidget#side_menu {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Dashboard_Title {\n"
"    background-color: none;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    font: 20pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Eat_Out_Image {\n"
"    background-image: url(:/images/pngaaa.com-2384833.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Grocery_Image {\n"
"    background-image: url(:/images/pngaaa.com-2138453.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Transportation_Image {\n"
"    background-image: url(:/images/pngaaa.com-2182093.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Free_Expense_Image {\n"
"    background-image: url(:/images/pngaaa.com-1261106.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Bills_Image {\n"
"    background-image: url(:/images/pngaaa.com-1433501.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Investment_Image {\n"
"    background-image: url(:/images/pngaaa.com-3584133.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Support_Image {\n"
"    background-image: url(:/images/pngaaa.com-2914571.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Goal_Image {\n"
"    background-image: url(:/images/pngaaa.com-848656.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:hover {\n"
"    background-image: url(:/button_image/Burger_button_hover.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:pressed {\n"
"    background-image: url(:/button_image/Burger_button_click.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#remove_button_watchlist {\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#remove_button_watchlist:hover {\n"
"    background-color: #ff6c6c;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#remove_button_watchlist:pressed {\n"
"    background-color: #aa0000;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Add_strategy:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Activation {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Activation:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Activation:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Blue_button {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Blue_button:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Blue_button:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Yellow_button {\n"
"    background-color: #a5bd1e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Yellow_button:hover {\n"
"    background-color: #e5ff54;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Yellow_button:pressed {\n"
"    background-color: #81960f;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #3a3a3a;\n"
"    width: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.average_actualy_m_wage_label_4 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_4.setGeometry(QtCore.QRect(40, 180, 271, 61))
        self.average_actualy_m_wage_label_4.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.average_actualy_m_wage_label_4.setWordWrap(True)
        self.average_actualy_m_wage_label_4.setObjectName("average_actualy_m_wage_label_4")
        self.state_comboBox = QtWidgets.QComboBox(parent=Form)
        self.state_comboBox.setGeometry(QtCore.QRect(360, 270, 211, 31))
        self.state_comboBox.setObjectName("state_comboBox")
        self.state_comboBox.addItem("")
        self.state_comboBox.addItem("")
        self.Yearly_federal_tax_tableView = QtWidgets.QTableView(parent=Form)
        self.Yearly_federal_tax_tableView.setGeometry(QtCore.QRect(40, 580, 561, 271))
        self.Yearly_federal_tax_tableView.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.Yearly_federal_tax_tableView.setObjectName("Yearly_federal_tax_tableView")
        self.state_tax_label = QtWidgets.QLabel(parent=Form)
        self.state_tax_label.setGeometry(QtCore.QRect(40, 260, 271, 61))
        self.state_tax_label.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.state_tax_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.state_tax_label.setWordWrap(True)
        self.state_tax_label.setObjectName("state_tax_label")
        self.average_actualy_m_wage_label_3 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_3.setGeometry(QtCore.QRect(360, 90, 150, 60))
        self.average_actualy_m_wage_label_3.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.average_actualy_m_wage_label_3.setWordWrap(True)
        self.average_actualy_m_wage_label_3.setObjectName("average_actualy_m_wage_label_3")
        self.average_actualy_m_wage_label_10 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_10.setGeometry(QtCore.QRect(40, 340, 271, 61))
        self.average_actualy_m_wage_label_10.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.average_actualy_m_wage_label_10.setWordWrap(True)
        self.average_actualy_m_wage_label_10.setObjectName("average_actualy_m_wage_label_10")
        self.average_actualy_m_wage_label_6 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_6.setGeometry(QtCore.QRect(360, 500, 150, 60))
        self.average_actualy_m_wage_label_6.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.average_actualy_m_wage_label_6.setWordWrap(True)
        self.average_actualy_m_wage_label_6.setObjectName("average_actualy_m_wage_label_6")
        self.average_actualy_m_wage_label = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label.setGeometry(QtCore.QRect(40, 20, 271, 61))
        self.average_actualy_m_wage_label.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.average_actualy_m_wage_label.setWordWrap(True)
        self.average_actualy_m_wage_label.setObjectName("average_actualy_m_wage_label")
        self.average_actualy_m_wage_lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.average_actualy_m_wage_lineEdit_2.setGeometry(QtCore.QRect(360, 190, 211, 31))
        self.average_actualy_m_wage_lineEdit_2.setText("")
        self.average_actualy_m_wage_lineEdit_2.setObjectName("average_actualy_m_wage_lineEdit_2")
        self.average_actualy_m_wage_label_2 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_2.setGeometry(QtCore.QRect(40, 100, 271, 61))
        self.average_actualy_m_wage_label_2.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.average_actualy_m_wage_label_2.setWordWrap(True)
        self.average_actualy_m_wage_label_2.setObjectName("average_actualy_m_wage_label_2")
        self.average_actualy_m_wage_label_8 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_8.setGeometry(QtCore.QRect(40, 420, 271, 61))
        self.average_actualy_m_wage_label_8.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.average_actualy_m_wage_label_8.setWordWrap(True)
        self.average_actualy_m_wage_label_8.setObjectName("average_actualy_m_wage_label_8")
        self.Update_pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.Update_pushButton_5.setGeometry(QtCore.QRect(580, 510, 164, 38))
        self.Update_pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.Update_pushButton_5.setObjectName("Update_pushButton_5")
        self.average_actualy_m_wage_label_9 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_9.setGeometry(QtCore.QRect(360, 420, 150, 60))
        self.average_actualy_m_wage_label_9.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.average_actualy_m_wage_label_9.setWordWrap(True)
        self.average_actualy_m_wage_label_9.setObjectName("average_actualy_m_wage_label_9")
        self.average_actualy_m_wage_label_7 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_7.setGeometry(QtCore.QRect(40, 500, 271, 61))
        self.average_actualy_m_wage_label_7.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.average_actualy_m_wage_label_7.setWordWrap(True)
        self.average_actualy_m_wage_label_7.setObjectName("average_actualy_m_wage_label_7")
        self.average_actualy_m_wage_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.average_actualy_m_wage_lineEdit.setGeometry(QtCore.QRect(360, 30, 211, 31))
        self.average_actualy_m_wage_lineEdit.setText("")
        self.average_actualy_m_wage_lineEdit.setObjectName("average_actualy_m_wage_lineEdit")
        self.average_actualy_m_wage_label_11 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_11.setGeometry(QtCore.QRect(360, 340, 150, 60))
        self.average_actualy_m_wage_label_11.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.average_actualy_m_wage_label_11.setWordWrap(True)
        self.average_actualy_m_wage_label_11.setObjectName("average_actualy_m_wage_label_11")
        self.average_actualy_m_wage_label_12 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_12.setGeometry(QtCore.QRect(650, 660, 150, 60))
        self.average_actualy_m_wage_label_12.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.average_actualy_m_wage_label_12.setWordWrap(True)
        self.average_actualy_m_wage_label_12.setObjectName("average_actualy_m_wage_label_12")
        self.average_actualy_m_wage_label_13 = QtWidgets.QLabel(parent=Form)
        self.average_actualy_m_wage_label_13.setGeometry(QtCore.QRect(630, 580, 201, 61))
        self.average_actualy_m_wage_label_13.setStyleSheet("font: 500 16pt \"Nirmala UI\";")
        self.average_actualy_m_wage_label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.average_actualy_m_wage_label_13.setWordWrap(True)
        self.average_actualy_m_wage_label_13.setObjectName("average_actualy_m_wage_label_13")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.average_actualy_m_wage_label_4.setText(_translate("Form", "Actual Average Monthly Wage (AT) :"))
        self.state_comboBox.setItemText(0, _translate("Form", "Illinois"))
        self.state_comboBox.setItemText(1, _translate("Form", "Indiana"))
        self.state_tax_label.setText(_translate("Form", "State For Tax :"))
        self.average_actualy_m_wage_label_3.setText(_translate("Form", "$1,555,555.55"))
        self.average_actualy_m_wage_label_10.setText(_translate("Form", "State Tax :"))
        self.average_actualy_m_wage_label_6.setText(_translate("Form", "$1,555,555.55"))
        self.average_actualy_m_wage_label.setText(_translate("Form", "Actual Average Monthly Wage (AT) :"))
        self.average_actualy_m_wage_label_2.setText(_translate("Form", "Monthly Planned - (AT) :"))
        self.average_actualy_m_wage_label_8.setText(_translate("Form", "Yearly State Tax:"))
        self.Update_pushButton_5.setText(_translate("Form", "Confirm"))
        self.average_actualy_m_wage_label_9.setText(_translate("Form", "55%"))
        self.average_actualy_m_wage_label_7.setText(_translate("Form", "Yearly Wage Before Taxes :"))
        self.average_actualy_m_wage_label_11.setText(_translate("Form", "55%"))
        self.average_actualy_m_wage_label_12.setText(_translate("Form", "$1,555,555.55"))
        self.average_actualy_m_wage_label_13.setText(_translate("Form", "Yearly Wage After Taxes :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
