# Form implementation generated from reading ui file 'Dashboard_header_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dashboard_header_widget(object):
    def setupUi(self, Dashboard_header_widget):
        Dashboard_header_widget.setObjectName("Dashboard_header_widget")
        Dashboard_header_widget.resize(1920, 130)
        Dashboard_header_widget.setStyleSheet("QWidget {\n"
"        background-color: #2c2c2c;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font: 14pt \"Nirmala UI\";\n"
"}\n"
"QWidget#side_menu {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Dashboard_Title {\n"
"    background-color: none;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    font: 20pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Eat_Out_Image {\n"
"    background-image: url(:/images/pngaaa.com-2384833.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Grocery_Image {\n"
"    background-image: url(:/images/pngaaa.com-2138453.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Transportation_Image {\n"
"    background-image: url(:/images/pngaaa.com-2182093.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Free_Expense_Image {\n"
"    background-image: url(:/images/pngaaa.com-1261106.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Bills_Image {\n"
"    background-image: url(:/images/pngaaa.com-1433501.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Investment_Image {\n"
"    background-image: url(:/images/pngaaa.com-3584133.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Support_Image {\n"
"    background-image: url(:/images/pngaaa.com-2914571.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Goal_Image {\n"
"    background-image: url(:/images/pngaaa.com-848656.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:hover {\n"
"    background-image: url(:/button_image/Burger_button_hover.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:pressed {\n"
"    background-image: url(:/button_image/Burger_button_click.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#remove_button_watchlist {\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#remove_button_watchlist:hover {\n"
"    background-color: #ff6c6c;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#remove_button_watchlist:pressed {\n"
"    background-color: #aa0000;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Add_strategy:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Activation {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Activation:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Activation:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Blue_button {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Blue_button:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Blue_button:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Yellow_button {\n"
"    background-color: #a5bd1e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Yellow_button:hover {\n"
"    background-color: #e5ff54;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Yellow_button:pressed {\n"
"    background-color: #81960f;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #3a3a3a;\n"
"    width: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.label.setGeometry(QtCore.QRect(10, 30, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 700 26pt \"Arial\";")
        self.label.setObjectName("label")
        self.YTD_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.YTD_label.setGeometry(QtCore.QRect(370, 40, 101, 31))
        self.YTD_label.setObjectName("YTD_label")
        self.Eating_out_Image_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Eating_out_Image_label.setGeometry(QtCore.QRect(490, 10, 61, 61))
        self.Eating_out_Image_label.setObjectName("Eating_out_Image_label")
        self.Eating_out_Spent_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Eating_out_Spent_label.setGeometry(QtCore.QRect(560, 30, 91, 31))
        self.Eating_out_Spent_label.setText("")
        self.Eating_out_Spent_label.setObjectName("Eating_out_Spent_label")
        self.Eating_out_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Eating_out_label.setGeometry(QtCore.QRect(490, 80, 161, 31))
        self.Eating_out_label.setObjectName("Eating_out_label")
        self.Grocery_Image_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Grocery_Image_label.setGeometry(QtCore.QRect(670, 10, 61, 61))
        self.Grocery_Image_label.setObjectName("Grocery_Image_label")
        self.Grocery_Spent_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Grocery_Spent_label.setGeometry(QtCore.QRect(740, 30, 91, 31))
        self.Grocery_Spent_label.setText("")
        self.Grocery_Spent_label.setObjectName("Grocery_Spent_label")
        self.Grocery_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Grocery_label.setGeometry(QtCore.QRect(670, 80, 161, 31))
        self.Grocery_label.setObjectName("Grocery_label")
        self.Transportation_Image_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Transportation_Image_label.setGeometry(QtCore.QRect(850, 10, 61, 61))
        self.Transportation_Image_label.setObjectName("Transportation_Image_label")
        self.Transportation_Spent_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Transportation_Spent_label.setGeometry(QtCore.QRect(920, 30, 91, 31))
        self.Transportation_Spent_label.setText("")
        self.Transportation_Spent_label.setObjectName("Transportation_Spent_label")
        self.Transportation_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Transportation_label.setGeometry(QtCore.QRect(850, 80, 161, 31))
        self.Transportation_label.setObjectName("Transportation_label")
        self.Free_Expense_Image_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Free_Expense_Image_label.setGeometry(QtCore.QRect(1030, 10, 61, 61))
        self.Free_Expense_Image_label.setObjectName("Free_Expense_Image_label")
        self.Free_expense_Spent_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Free_expense_Spent_label.setGeometry(QtCore.QRect(1100, 30, 91, 31))
        self.Free_expense_Spent_label.setText("")
        self.Free_expense_Spent_label.setObjectName("Free_expense_Spent_label")
        self.Free_Expense_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Free_Expense_label.setGeometry(QtCore.QRect(1030, 80, 161, 31))
        self.Free_Expense_label.setObjectName("Free_Expense_label")
        self.Investment_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Investment_label.setGeometry(QtCore.QRect(1210, 80, 161, 31))
        self.Investment_label.setObjectName("Investment_label")
        self.Investment_Image_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Investment_Image_label.setGeometry(QtCore.QRect(1210, 10, 61, 61))
        self.Investment_Image_label.setObjectName("Investment_Image_label")
        self.Investment_Spent_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Investment_Spent_label.setGeometry(QtCore.QRect(1280, 30, 91, 31))
        self.Investment_Spent_label.setText("")
        self.Investment_Spent_label.setObjectName("Investment_Spent_label")
        self.Bills_Spent_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Bills_Spent_label.setGeometry(QtCore.QRect(1460, 30, 91, 31))
        self.Bills_Spent_label.setText("")
        self.Bills_Spent_label.setObjectName("Bills_Spent_label")
        self.Bills_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Bills_label.setGeometry(QtCore.QRect(1390, 80, 161, 31))
        self.Bills_label.setObjectName("Bills_label")
        self.Bills_Image_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Bills_Image_label.setGeometry(QtCore.QRect(1390, 10, 61, 61))
        self.Bills_Image_label.setObjectName("Bills_Image_label")
        self.Support_Spent_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Support_Spent_label.setGeometry(QtCore.QRect(1640, 30, 91, 31))
        self.Support_Spent_label.setText("")
        self.Support_Spent_label.setObjectName("Support_Spent_label")
        self.Support_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Support_label.setGeometry(QtCore.QRect(1570, 80, 161, 31))
        self.Support_label.setObjectName("Support_label")
        self.Support_Image_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Support_Image_label.setGeometry(QtCore.QRect(1570, 10, 61, 61))
        self.Support_Image_label.setObjectName("Support_Image_label")
        self.Bills_Spent_label_2 = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Bills_Spent_label_2.setGeometry(QtCore.QRect(1820, 30, 91, 31))
        self.Bills_Spent_label_2.setText("")
        self.Bills_Spent_label_2.setObjectName("Bills_Spent_label_2")
        self.Goal_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Goal_label.setGeometry(QtCore.QRect(1750, 80, 161, 31))
        self.Goal_label.setObjectName("Goal_label")
        self.Goal_Image_label = QtWidgets.QLabel(parent=Dashboard_header_widget)
        self.Goal_Image_label.setGeometry(QtCore.QRect(1750, 10, 61, 61))
        self.Goal_Image_label.setObjectName("Goal_Image_label")
        self.line = QtWidgets.QFrame(parent=Dashboard_header_widget)
        self.line.setGeometry(QtCore.QRect(0, 125, 1920, 10))
        self.line.setStyleSheet("background-color: #181818;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dashboard_header_widget)
        QtCore.QMetaObject.connectSlotsByName(Dashboard_header_widget)

    def retranslateUi(self, Dashboard_header_widget):
        _translate = QtCore.QCoreApplication.translate
        Dashboard_header_widget.setWindowTitle(_translate("Dashboard_header_widget", "Form"))
        self.label.setText(_translate("Dashboard_header_widget", "Financial Dashboard"))
        self.YTD_label.setText(_translate("Dashboard_header_widget", "Spend YTD:"))
        self.Eating_out_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/eating_out_label_61x61.png\"/></p></body></html>"))
        self.Eating_out_label.setText(_translate("Dashboard_header_widget", "Eating-Out"))
        self.Grocery_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/grocery_label_61x61.png\"/></p></body></html>"))
        self.Grocery_label.setText(_translate("Dashboard_header_widget", "Grocery"))
        self.Transportation_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/transportation_label_61x61.png\"/></p></body></html>"))
        self.Transportation_label.setText(_translate("Dashboard_header_widget", "Transportation"))
        self.Free_Expense_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/Free_expense_label_61x61.png\"/></p></body></html>"))
        self.Free_Expense_label.setText(_translate("Dashboard_header_widget", "Free Expense"))
        self.Investment_label.setText(_translate("Dashboard_header_widget", "Investment"))
        self.Investment_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/investments_label_61x61.png\"/></p></body></html>"))
        self.Bills_label.setText(_translate("Dashboard_header_widget", "Bills"))
        self.Bills_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/bills_label_61x61.png\"/></p></body></html>"))
        self.Support_label.setText(_translate("Dashboard_header_widget", "Support"))
        self.Support_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/support_label_61x61.png\"/></p></body></html>"))
        self.Goal_label.setText(_translate("Dashboard_header_widget", "Goal"))
        self.Goal_Image_label.setText(_translate("Dashboard_header_widget", "<html><head/><body><p><img src=\":/images/images/goal_label_61x61.png\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dashboard_header_widget = QtWidgets.QWidget()
    ui = Ui_Dashboard_header_widget()
    ui.setupUi(Dashboard_header_widget)
    Dashboard_header_widget.show()
    sys.exit(app.exec())
