# Form implementation generated from reading ui file 'portfolio_stats.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 680)
        Form.setStyleSheet("QWidget {\n"
"        background-color: #2c2c2c;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font: 14pt \"Nirmala UI\";\n"
"}\n"
"QWidget#side_menu {\n"
"    background-color: #4e5564;\n"
"    color: #ffffff;\n"
"    border: 1px solid #4e5564;\n"
"    border-radius: 16px;\n"
"    font: 14pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Dashboard_Title {\n"
"    background-color: none;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    font: 20pt \"Nirmala UI\";\n"
"}\n"
"QLabel#Eat_Out_Image {\n"
"    background-image: url(:/images/pngaaa.com-2384833.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Grocery_Image {\n"
"    background-image: url(:/images/pngaaa.com-2138453.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Transportation_Image {\n"
"    background-image: url(:/images/pngaaa.com-2182093.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Free_Expense_Image {\n"
"    background-image: url(:/images/pngaaa.com-1261106.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Bills_Image {\n"
"    background-image: url(:/images/pngaaa.com-1433501.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Investment_Image {\n"
"    background-image: url(:/images/pngaaa.com-3584133.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Support_Image {\n"
"    background-image: url(:/images/pngaaa.com-2914571.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QLabel#Goal_Image {\n"
"    background-image: url(:/images/pngaaa.com-848656.png);\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:hover {\n"
"    background-image: url(:/button_image/Burger_button_hover.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#side_menu_button:pressed {\n"
"    background-image: url(:/button_image/Burger_button_click.png);\n"
"    background-color: #5a5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton#remove_button_watchlist {\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#remove_button_watchlist:hover {\n"
"    background-color: #ff6c6c;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#remove_button_watchlist:pressed {\n"
"    background-color: #aa0000;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Add_strategy:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Add_strategy:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Activation {\n"
"    background-color: #00ad0e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Activation:hover {\n"
"    background-color: #67ff74;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Activation:pressed {\n"
"    background-color: #006408;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Blue_button {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Blue_button:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Blue_button:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QPushButton#Yellow_button {\n"
"    background-color: #a5bd1e;\n"
"    border: 1px solid #ffffff;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton#Yellow_button:hover {\n"
"    background-color: #e5ff54;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QPushButton#Yellow_button:pressed {\n"
"    background-color: #81960f;\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #4d4d4d;\n"
"    border: 1px solid #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #444444;\n"
"    border-radius: 7px;\n"
"    background-color: #2e2e2e;\n"
"    text-align: center;\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #3a3a3a;\n"
"    width: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    width: 10px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #3a3a3a;\n"
"    height: 10px;\n"
"    margin: 0px 16px 0 16px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #444444;\n"
"    border-radius: 5px;\n"
"}\n"
"QTabWidget {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #2e2e2e;\n"
"    color: #b1b1b1;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border: none;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background-color: #3a3a3a;\n"
"    color: white;\n"
"}")
        self.update_account_label_6 = QtWidgets.QLabel(parent=Form)
        self.update_account_label_6.setGeometry(QtCore.QRect(20, 130, 121, 31))
        self.update_account_label_6.setStyleSheet("font: 700 20pt \"Nirmala UI\";")
        self.update_account_label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.update_account_label_6.setObjectName("update_account_label_6")
        self.amount_year_start_total_label = QtWidgets.QLabel(parent=Form)
        self.amount_year_start_total_label.setGeometry(QtCore.QRect(220, 200, 171, 31))
        self.amount_year_start_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amount_year_start_total_label.setWordWrap(True)
        self.amount_year_start_total_label.setObjectName("amount_year_start_total_label")
        self.amount_last_month_change_label = QtWidgets.QLabel(parent=Form)
        self.amount_last_month_change_label.setGeometry(QtCore.QRect(220, 350, 171, 31))
        self.amount_last_month_change_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amount_last_month_change_label.setWordWrap(True)
        self.amount_last_month_change_label.setObjectName("amount_last_month_change_label")
        self.evaluate_Month_label_2 = QtWidgets.QLabel(parent=Form)
        self.evaluate_Month_label_2.setGeometry(QtCore.QRect(470, 130, 181, 28))
        self.evaluate_Month_label_2.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.evaluate_Month_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.evaluate_Month_label_2.setObjectName("evaluate_Month_label_2")
        self.layoutWidget_4 = QtWidgets.QWidget(parent=Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 590, 911, 81))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.remove_account_label = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.remove_account_label.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.remove_account_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.remove_account_label.setObjectName("remove_account_label")
        self.gridLayout_9.addWidget(self.remove_account_label, 0, 0, 1, 1)
        self.month_remove_label = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.month_remove_label.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.month_remove_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.month_remove_label.setObjectName("month_remove_label")
        self.gridLayout_9.addWidget(self.month_remove_label, 0, 1, 1, 1)
        self.remove_account_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget_4)
        self.remove_account_comboBox.setMinimumSize(QtCore.QSize(0, 45))
        self.remove_account_comboBox.setObjectName("remove_account_comboBox")
        self.remove_account_comboBox.addItem("")
        self.remove_account_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.remove_account_comboBox, 1, 0, 1, 1)
        self.remove_month_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget_4)
        self.remove_month_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.remove_month_dateEdit.setMaximumDate(QtCore.QDate(2024, 12, 31))
        self.remove_month_dateEdit.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.remove_month_dateEdit.setObjectName("remove_month_dateEdit")
        self.gridLayout_9.addWidget(self.remove_month_dateEdit, 1, 1, 1, 1)
        self.remove_confirm_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget_4)
        self.remove_confirm_pushButton.setMaximumSize(QtCore.QSize(164, 16777215))
        self.remove_confirm_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #c30000;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ff5a5a;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8c0000;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.remove_confirm_pushButton.setObjectName("remove_confirm_pushButton")
        self.gridLayout_9.addWidget(self.remove_confirm_pushButton, 1, 2, 1, 1)
        self.update_account_label_8 = QtWidgets.QLabel(parent=Form)
        self.update_account_label_8.setGeometry(QtCore.QRect(200, 130, 201, 31))
        self.update_account_label_8.setStyleSheet("font: 700 20pt \"Nirmala UI\";")
        self.update_account_label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.update_account_label_8.setObjectName("update_account_label_8")
        self.layoutWidget_5 = QtWidgets.QWidget(parent=Form)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 500, 911, 81))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.add_account_doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.layoutWidget_5)
        self.add_account_doubleSpinBox.setMaximum(1000000000.99)
        self.add_account_doubleSpinBox.setSingleStep(0.01)
        self.add_account_doubleSpinBox.setProperty("value", 1555555.0)
        self.add_account_doubleSpinBox.setObjectName("add_account_doubleSpinBox")
        self.gridLayout_10.addWidget(self.add_account_doubleSpinBox, 1, 1, 1, 1)
        self.update_account_label_9 = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.update_account_label_9.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.update_account_label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.update_account_label_9.setObjectName("update_account_label_9")
        self.gridLayout_10.addWidget(self.update_account_label_9, 0, 0, 1, 1)
        self.add_month_label = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.add_month_label.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.add_month_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.add_month_label.setObjectName("add_month_label")
        self.gridLayout_10.addWidget(self.add_month_label, 0, 2, 1, 1)
        self.account_name_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.account_name_lineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.account_name_lineEdit.setObjectName("account_name_lineEdit")
        self.gridLayout_10.addWidget(self.account_name_lineEdit, 1, 0, 1, 1)
        self.add_amount_label = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.add_amount_label.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.add_amount_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.add_amount_label.setObjectName("add_amount_label")
        self.gridLayout_10.addWidget(self.add_amount_label, 0, 1, 1, 1)
        self.add_month_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget_5)
        self.add_month_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.add_month_dateEdit.setMaximumDate(QtCore.QDate(2024, 12, 31))
        self.add_month_dateEdit.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.add_month_dateEdit.setObjectName("add_month_dateEdit")
        self.gridLayout_10.addWidget(self.add_month_dateEdit, 1, 2, 1, 1)
        self.add_confirm_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget_5)
        self.add_confirm_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00aa00;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00ff00;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #007900;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.add_confirm_pushButton.setObjectName("add_confirm_pushButton")
        self.gridLayout_10.addWidget(self.add_confirm_pushButton, 1, 3, 1, 1)
        self.month_change_label = QtWidgets.QLabel(parent=Form)
        self.month_change_label.setGeometry(QtCore.QRect(470, 390, 171, 31))
        self.month_change_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.month_change_label.setWordWrap(True)
        self.month_change_label.setObjectName("month_change_label")
        self.amount_exp_end_label = QtWidgets.QLabel(parent=Form)
        self.amount_exp_end_label.setGeometry(QtCore.QRect(220, 430, 171, 31))
        self.amount_exp_end_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amount_exp_end_label.setWordWrap(True)
        self.amount_exp_end_label.setObjectName("amount_exp_end_label")
        self.exp_end_label = QtWidgets.QLabel(parent=Form)
        self.exp_end_label.setGeometry(QtCore.QRect(40, 390, 161, 91))
        self.exp_end_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.exp_end_label.setWordWrap(True)
        self.exp_end_label.setObjectName("exp_end_label")
        self.year_start_total_label = QtWidgets.QLabel(parent=Form)
        self.year_start_total_label.setGeometry(QtCore.QRect(40, 160, 161, 91))
        self.year_start_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.year_start_total_label.setWordWrap(True)
        self.year_start_total_label.setObjectName("year_start_total_label")
        self.month_end_label = QtWidgets.QLabel(parent=Form)
        self.month_end_label.setGeometry(QtCore.QRect(470, 290, 161, 81))
        self.month_end_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.month_end_label.setWordWrap(True)
        self.month_end_label.setObjectName("month_end_label")
        self.layoutWidget_6 = QtWidgets.QWidget(parent=Form)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 10, 911, 81))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.update_account_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget_6)
        self.update_account_comboBox.setMinimumSize(QtCore.QSize(0, 45))
        self.update_account_comboBox.setObjectName("update_account_comboBox")
        self.update_account_comboBox.addItem("")
        self.update_account_comboBox.addItem("")
        self.gridLayout_11.addWidget(self.update_account_comboBox, 1, 0, 1, 1)
        self.update_amount_doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.layoutWidget_6)
        self.update_amount_doubleSpinBox.setMaximum(1000000000.99)
        self.update_amount_doubleSpinBox.setSingleStep(0.01)
        self.update_amount_doubleSpinBox.setProperty("value", 1555555.0)
        self.update_amount_doubleSpinBox.setObjectName("update_amount_doubleSpinBox")
        self.gridLayout_11.addWidget(self.update_amount_doubleSpinBox, 1, 1, 1, 1)
        self.update_amount_label = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.update_amount_label.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.update_amount_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.update_amount_label.setObjectName("update_amount_label")
        self.gridLayout_11.addWidget(self.update_amount_label, 0, 1, 1, 1)
        self.update_month_label = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.update_month_label.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.update_month_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.update_month_label.setObjectName("update_month_label")
        self.gridLayout_11.addWidget(self.update_month_label, 0, 2, 1, 1)
        self.update_month_dateEdit = QtWidgets.QDateEdit(parent=self.layoutWidget_6)
        self.update_month_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.update_month_dateEdit.setMaximumDate(QtCore.QDate(2024, 12, 31))
        self.update_month_dateEdit.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.update_month_dateEdit.setObjectName("update_month_dateEdit")
        self.gridLayout_11.addWidget(self.update_month_dateEdit, 1, 2, 1, 1)
        self.update_account_label_10 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.update_account_label_10.setStyleSheet("font: 700 16pt \"Nirmala UI\";")
        self.update_account_label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.update_account_label_10.setObjectName("update_account_label_10")
        self.gridLayout_11.addWidget(self.update_account_label_10, 0, 0, 1, 1)
        self.update_confirm_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget_6)
        self.update_confirm_pushButton.setMaximumSize(QtCore.QSize(164, 16777215))
        self.update_confirm_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #0003bb;\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4446d1;\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #000277;\n"
"    border: 1px solid #5a5a5a;\n"
"}")
        self.update_confirm_pushButton.setObjectName("update_confirm_pushButton")
        self.gridLayout_11.addWidget(self.update_confirm_pushButton, 1, 3, 1, 1)
        self.evaluate_Month_dateEdit_2 = QtWidgets.QDateEdit(parent=Form)
        self.evaluate_Month_dateEdit_2.setGeometry(QtCore.QRect(470, 170, 299, 28))
        self.evaluate_Month_dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.evaluate_Month_dateEdit_2.setMaximumDate(QtCore.QDate(2024, 12, 31))
        self.evaluate_Month_dateEdit_2.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.evaluate_Month_dateEdit_2.setObjectName("evaluate_Month_dateEdit_2")
        self.last_month_change_label = QtWidgets.QLabel(parent=Form)
        self.last_month_change_label.setGeometry(QtCore.QRect(40, 310, 161, 91))
        self.last_month_change_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.last_month_change_label.setWordWrap(True)
        self.last_month_change_label.setObjectName("last_month_change_label")
        self.avg_change_label = QtWidgets.QLabel(parent=Form)
        self.avg_change_label.setGeometry(QtCore.QRect(40, 230, 161, 91))
        self.avg_change_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.avg_change_label.setWordWrap(True)
        self.avg_change_label.setObjectName("avg_change_label")
        self.start_month_label = QtWidgets.QLabel(parent=Form)
        self.start_month_label.setGeometry(QtCore.QRect(470, 210, 161, 81))
        self.start_month_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.start_month_label.setWordWrap(True)
        self.start_month_label.setObjectName("start_month_label")
        self.amount_avg_change_label = QtWidgets.QLabel(parent=Form)
        self.amount_avg_change_label.setGeometry(QtCore.QRect(220, 270, 171, 31))
        self.amount_avg_change_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amount_avg_change_label.setWordWrap(True)
        self.amount_avg_change_label.setObjectName("amount_avg_change_label")
        self.amount_start_month_label = QtWidgets.QLabel(parent=Form)
        self.amount_start_month_label.setGeometry(QtCore.QRect(660, 250, 171, 31))
        self.amount_start_month_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amount_start_month_label.setWordWrap(True)
        self.amount_start_month_label.setObjectName("amount_start_month_label")
        self.amount_month_change_label = QtWidgets.QLabel(parent=Form)
        self.amount_month_change_label.setGeometry(QtCore.QRect(660, 390, 171, 31))
        self.amount_month_change_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amount_month_change_label.setWordWrap(True)
        self.amount_month_change_label.setObjectName("amount_month_change_label")
        self.amount_month_end_label = QtWidgets.QLabel(parent=Form)
        self.amount_month_end_label.setGeometry(QtCore.QRect(660, 330, 171, 31))
        self.amount_month_end_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amount_month_end_label.setWordWrap(True)
        self.amount_month_end_label.setObjectName("amount_month_end_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.update_account_label_6.setText(_translate("Form", "Total :"))
        self.amount_year_start_total_label.setText(_translate("Form", "$1,555,555.55"))
        self.amount_last_month_change_label.setText(_translate("Form", "$1,555,555.55"))
        self.evaluate_Month_label_2.setText(_translate("Form", "Evaluate Month"))
        self.remove_account_label.setText(_translate("Form", "Remove Account"))
        self.month_remove_label.setText(_translate("Form", "Month"))
        self.remove_account_comboBox.setItemText(0, _translate("Form", "Chase Freedom Unlimited"))
        self.remove_account_comboBox.setItemText(1, _translate("Form", "Chase Checking"))
        self.remove_month_dateEdit.setDisplayFormat(_translate("Form", "M/yyyy"))
        self.remove_confirm_pushButton.setText(_translate("Form", "Remove"))
        self.update_account_label_8.setText(_translate("Form", "$1,555,555.00"))
        self.update_account_label_9.setText(_translate("Form", "Add Account"))
        self.add_month_label.setText(_translate("Form", "Month"))
        self.add_amount_label.setText(_translate("Form", "Amount"))
        self.add_month_dateEdit.setDisplayFormat(_translate("Form", "M/yyyy"))
        self.add_confirm_pushButton.setText(_translate("Form", "Add"))
        self.month_change_label.setText(_translate("Form", "Change For Month :"))
        self.amount_exp_end_label.setText(_translate("Form", "$1,555,555.55"))
        self.exp_end_label.setText(_translate("Form", "Expected End Value For Year :"))
        self.year_start_total_label.setText(_translate("Form", "Starting Total For Year :"))
        self.month_end_label.setText(_translate("Form", "Ending Total For Month :"))
        self.update_account_comboBox.setItemText(0, _translate("Form", "Chase Freedom Unlimited"))
        self.update_account_comboBox.setItemText(1, _translate("Form", "Chase Checking"))
        self.update_amount_label.setText(_translate("Form", "Amount"))
        self.update_month_label.setText(_translate("Form", "Month"))
        self.update_month_dateEdit.setDisplayFormat(_translate("Form", "M/yyyy"))
        self.update_account_label_10.setText(_translate("Form", "Update Account"))
        self.update_confirm_pushButton.setText(_translate("Form", "Update"))
        self.evaluate_Month_dateEdit_2.setDisplayFormat(_translate("Form", "M/yyyy"))
        self.last_month_change_label.setText(_translate("Form", "Portfolio Change From Last Month :"))
        self.avg_change_label.setText(_translate("Form", "Average Portfolio Change This Year :"))
        self.start_month_label.setText(_translate("Form", "Starting Total For Month :"))
        self.amount_avg_change_label.setText(_translate("Form", "$1,555,555.55"))
        self.amount_start_month_label.setText(_translate("Form", "$1,555,555.55"))
        self.amount_month_change_label.setText(_translate("Form", "$1,555,555.55"))
        self.amount_month_end_label.setText(_translate("Form", "$1,555,555.55"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
